# Generated by Django 5.1.3 on 2025-09-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_details', models.JSONField(blank=True, null=True)),
                ('seller_details', models.JSONField(blank=True, null=True)),
                ('buyer_details', models.JSONField(blank=True, null=True)),
                ('property_details', models.JSONField(blank=True, null=True)),
                ('khasra_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
