# Generated by Django 5.1.3 on 2025-09-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0002_scrapedrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='buyer_details',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='khasra_details',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='property_details',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='registration_details',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='seller_details',
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='bhu_adhikar_rin_pustika_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bhu-Adhikar Rin Pustika No.'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='buyer_guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Buyer Guardian's Name"),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Buyer Name'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='buyer_party_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Buyer Party Type'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='deed_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Deed Type'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Districts'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='district_property',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='document_registration_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Document Registration No.'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='east_boundary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='East'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='house_flat_plot_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='House/Flat No./Plot No.'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='khasra_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Khasra No'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='lagaan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lagaan'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='north_boundary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='North'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PIN Code'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='property_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Property ID'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Property Type'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='registration_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration Date'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='seller_guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Seller Guardian's Name"),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='seller_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seller Name'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='seller_party_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Seller Party Type'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='south_boundary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='South'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='sub_area_road',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Area/Road'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='tehsil_local_body',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tehsil/ Local Body'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='tehsil_locality_property',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tehsil/Locality'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='total_area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Total Area'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='transact_area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transact Area'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='type_of_area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type Of Area'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Village'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='ward_colony',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ward/Colony'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='ward_village_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ward/Village Name'),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='west_boundary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='West'),
        ),
        migrations.AlterField(
            model_name='scrapedrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
