# Generated by Django 5.1.3 on 2025-09-13 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0003_remove_scrapedrecord_buyer_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='bhu_adhikar_rin_pustika_no',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='buyer_guardian_name',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='buyer_party_type',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='country',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='deed_type',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='district',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='district_property',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='document_registration_no',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='east_boundary',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='house_flat_plot_no',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='khasra_no',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='lagaan',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='north_boundary',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='seller_guardian_name',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='seller_party_type',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='south_boundary',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='state',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='sub_area_road',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='tehsil_local_body',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='tehsil_locality_property',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='total_area',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='transact_area',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='type_of_area',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='village',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='ward_colony',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='ward_village_name',
        ),
        migrations.RemoveField(
            model_name='scrapedrecord',
            name='west_boundary',
        ),
        migrations.AlterField(
            model_name='scrapedrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='BuyerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='scraper_app.scrapedrecord')),
            ],
        ),
        migrations.CreateModel(
            name='KhasraDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khasra_number', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khasras', to='scraper_app.scrapedrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ward_colony', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='scraper_app.scrapedrecord')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.CharField(blank=True, max_length=100, null=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='scraper_app.scrapedrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SellerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='scraper_app.scrapedrecord')),
            ],
        ),
    ]
