# Generated by Django 5.1.3 on 2025-09-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0004_remove_scrapedrecord_bhu_adhikar_rin_pustika_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khasradetail',
            name='record',
        ),
        migrations.RemoveField(
            model_name='propertydetail',
            name='record',
        ),
        migrations.RemoveField(
            model_name='registrationdetail',
            name='record',
        ),
        migrations.RemoveField(
            model_name='sellerdetail',
            name='record',
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='buyer_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='khasra_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='property_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='registration_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedrecord',
            name='seller_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BuyerDetail',
        ),
        migrations.DeleteModel(
            name='KhasraDetail',
        ),
        migrations.DeleteModel(
            name='PropertyDetail',
        ),
        migrations.DeleteModel(
            name='RegistrationDetail',
        ),
        migrations.DeleteModel(
            name='SellerDetail',
        ),
    ]
