# Generated by Django 5.1.3 on 2025-09-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0005_remove_khasradetail_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingstatus',
            name='message',
        ),
        migrations.AddField(
            model_name='scrapingstatus',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapingstatus',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
