# Generated by Django 5.1.3 on 2025-09-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0006_remove_scrapingstatus_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingstatus',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='scrapingstatus',
            name='started_at',
        ),
        migrations.AddField(
            model_name='scrapingstatus',
            name='message',
            field=models.CharField(default='No message', max_length=255),
        ),
    ]
