# Generated by Django 5.1.3 on 2025-09-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0008_scrapingrun_scrapingstatus_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingstatus',
            name='run',
        ),
        migrations.RemoveField(
            model_name='scrapingstatus',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='scrapingstatus',
            name='message',
            field=models.CharField(default='No message', max_length=255),
        ),
        migrations.DeleteModel(
            name='ScrapingRun',
        ),
    ]
