# Generated by Django 5.1.3 on 2025-09-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0010_scrapingrun_scrapingstatus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingstatus',
            name='captcha_image',
            field=models.ImageField(blank=True, null=True, upload_to='captchas/'),
        ),
    ]
