# Generated by Django 5.1.3 on 2025-09-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0011_scrapingstatus_captcha_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingstatus',
            name='captcha_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
